Trawell_FINAL1/Trawell_FINAL1/Models/Activity_photo.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trawell_FINAL1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity_photo
    {
        public int id { get; set; }
        public string photo_path { get; set; }
        public int activ_id { get; set; }
    
        public virtual Activity Activity { get; set; }
    }
}

Trawell_FINAL1/Trawell_FINAL1/Areas/Admin/Controllers/Activity_photoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.IO;
using Trawell_FINAL1.Models;

namespace Trawell_FINAL1.Areas.Admin.Controllers
{
    public class Activity_photoController : Controller
    {
        private Trawell_DbaseEntities1 db = new Trawell_DbaseEntities1();

        // GET: Admin/Activity_photo
        public ActionResult Index()
        {
            var activity_photo = db.Activity_photo.Include(a => a.Activity);
            return View(activity_photo.ToList());
        }

        // GET: Admin/Activity_photo/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Activity_photo activity_photo = db.Activity_photo.Find(id);
            if (activity_photo == null)
            {
                return HttpNotFound();
            }
            return View(activity_photo);
        }

        // GET: Admin/Activity_photo/Create
        public ActionResult Create()
        {
            ViewBag.activ_id = new SelectList(db.Activities, "id", "activ_name");
            return View();
        }

        // POST: Admin/Activity_photo/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,photo_path,activ_id")] Activity_photo activity_photo,HttpPostedFileBase photo_path)
        {
          
            if (ModelState.IsValid)
            {
                if (photo_path.ContentType != "image/png" && photo_path.ContentType != "image/jpg")
                {
                    Session["Erorr"] = "Incorrect format";

                }
                string filename = DateTime.Now.ToString("ddMMyyyyHHmmssffff") + photo_path.FileName;
                string path = Path.Combine(Server.MapPath("~/Areas/Admin/Uploads"), filename);
                photo_path.SaveAs(path);
                activity_photo.photo_path = filename;
                db.Activity_photo.Add(activity_photo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.activ_id = new SelectList(db.Activities, "id", "activ_name", activity_photo.activ_id);
            return View(activity_photo);
        }

        // GET: Admin/Activity_photo/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Activity_photo activity_photo = db.Activity_photo.Find(id);
            if (activity_photo == null)
            {
                return HttpNotFound();
            }
            ViewBag.activ_id = new SelectList(db.Activities, "id", "activ_name", activity_photo.activ_id);
            return View(activity_photo);
        }

        // POST: Admin/Activity_photo/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,photo_path,activ_id")] Activity_photo activity_photo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(activity_photo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.activ_id = new SelectList(db.Activities, "id", "activ_name", activity_photo.activ_id);
            return View(activity_photo);
        }

        // GET: Admin/Activity_photo/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Activity_photo activity_photo = db.Activity_photo.Find(id);
            if (activity_photo == null)
            {
                return HttpNotFound();
            }
            return View(activity_photo);
        }

        // POST: Admin/Activity_photo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Activity_photo activity_photo = db.Activity_photo.Find(id);
            db.Activity_photo.Remove(activity_photo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Trawell_FINAL1/Trawell_FINAL1/Areas/Admin/Views/Activity_photo/Create.cshtml
@model Trawell_FINAL1.Models.Activity_photo

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/AdminPageView.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("create","Activity_photo",FormMethod.Post,new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Activity_photo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.photo_path, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.photo_path, new { htmlAttributes = new { @class = "form-control",@type="file" } })
                @Html.ValidationMessageFor(model => model.photo_path, "", new { @class = "text-danger" })
            </div>
        </div>
        @if (Session["Erorr"] != null) {

            <div class="alert alert-info">
                @Session["Erorr"]
            </div>
            @( Session["Erorr"]=null)
        }
        <div class="form-group">
            @Html.LabelFor(model => model.activ_id, "activ_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("activ_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.activ_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Trawell_FINAL1/Trawell_FINAL1/Areas/Admin/Views/Activity_photo/Delete.cshtml
@model Trawell_FINAL1.Models.Activity_photo

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/AdminPageView.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Activity_photo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.photo_path)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.photo_path)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Activity.activ_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Activity.activ_name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Trawell_FINAL1/Trawell_FINAL1/Areas/Admin/Views/Activity_photo/Details.cshtml
@model Trawell_FINAL1.Models.Activity_photo

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/AdminPageView.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Activity_photo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.photo_path)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.photo_path)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Activity.activ_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Activity.activ_name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Trawell_FINAL1/Trawell_FINAL1/Areas/Admin/Views/Activity_photo/Edit.cshtml
@model Trawell_FINAL1.Models.Activity_photo

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/AdminPageView.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Activity_photo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.photo_path, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.photo_path, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.photo_path, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.activ_id, "activ_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("activ_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.activ_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Trawell_FINAL1/Trawell_FINAL1/Areas/Admin/Views/Activity_photo/Index.cshtml
@model IEnumerable<Trawell_FINAL1.Models.Activity_photo>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminPageView.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.photo_path)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Activity.activ_name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <img src="~/Areas/Admin/Uploads/@Html.DisplayFor(modelItem => item.photo_path)"width="100"height="100" ;  />   
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Activity.activ_name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>